/**:
  ros__parameters:
    left_target_pose_list:
    #   x, y, z, roll, pitch, yaw, grasp
      - "0.5, -0.5, 0.15, 0, 3.14, 0.0" # 2
    right_target_pose_list:
    #  x, y, z, roll, pitch, yaw, grasp
      - "0.5, 0.45, 0.15, 0, 3.14, 0.0" # 3

#     6
#   4   5
# 1   2   3