/**:
  ros__parameters:
    left_target_pose_list:
    #   x, y, z, roll, pitch, yaw, grasp
      - "0.5, -0.3, 0.4, 0, 3.14, 1.57, 0.1"
      - "0.5, -0.3, 0.15, 0, 3.14, 1.57, 0.42"
      - "0.5, -0.3, 0.4, 1.57, -1.57, 0, 0.42"
      - "0.5, -0.33, 0.4, 1.57, -1.57, 0, 0.42"
    right_target_pose_list:
    #  x, y, z, roll, pitch, yaw, grasp
      - "0.5, 0.3, 0.4, 0, 3.14, 1.57, 0.0"
      - "0.5, 0.3, 0.15, 0, 3.14, 1.57, 0.42"
      - "0.5, 0.3, 0.4, -1.57, 1.57, 0, 0.42"
      - "0.5, 0.33, 0.4, -1.57, 1.57, 0, 0.42"